sonar.organization=aws774
sonar.projectKey=AWS774_SDS_Release

sonar.sources=lib
sonar.language=dart

sonar.sourceEncoding=UTF-8

# Optional tapi penting buat Flutter
sonar.dart.analyzer.reportPaths=analysis-report.txt