sonar.projectKey=AWS774_SDS
sonar.organization=aws774

sonar.projectName=CoolerBox Mobile App
sonar.projectVersion=1.0

sonar.sources=lib
sonar.exclusions=**/*.g.dart,**/*.freezed.dart

sonar.sourceEncoding=UTF-8